AssetslnWeb/Controllers/AssetManagement/AssetDashboardController.cs
using AssetslnWeb.BAL;
using AssetslnWeb.BAL.AssetManagement;
using AssetslnWeb.Models;
using AssetslnWeb.Models.AssetManagement;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AssetslnWeb.Controllers.AssetManagement
{
    public class AssetDashboardController : Controller
    {
        AM_AssetMainModel assetMainModel = new AM_AssetMainModel();

        // declare object to get pending and my request data
        List<AM_AssetsApplyModel> PendingReqModels = new List<AM_AssetsApplyModel>();
        List<AM_AssetsApplyModel> MyRequestModels = new List<AM_AssetsApplyModel>();
        List<AM_BasicInfoModel> basicInfoModels = new List<AM_BasicInfoModel>();

        // call bal function to get pending and my request data
        AM_AssetsApplyBal PendingReqBals = new AM_AssetsApplyBal();
        AM_AssetsApplyBal MyRequestBal = new AM_AssetsApplyBal();

        // create asset apply model object
        AM_AssetsApplyModel applyModel = new AM_AssetsApplyModel();

        // call assetsapply bal class method
        AM_AssetsApplyBal assetsApplyBal = new AM_AssetsApplyBal();

        // create object of AssetApplyDetails model and bal
        List<AM_AssetsApplyDetailsModel> assetsApplyDetailsModels = new List<AM_AssetsApplyDetailsModel>();
        AM_AssetsApplyDetailsBal assetsApplyDetailsBal = new AM_AssetsApplyDetailsBal();

        // create object of AssetHistory model and bal
        List<AM_AssetsHistoryModel> assetsHistoryModel = new List<AM_AssetsHistoryModel>();
        AM_AssetsHistoryBal assetsHistoryBal = new AM_AssetsHistoryBal();

        // create object to get AssetsApproverData
        List<AM_AssetsApproverModel> assetsApproverModels = new List<AM_AssetsApproverModel>();
        AM_AssetsApproverBal assetsApproverBal = new AM_AssetsApproverBal();
        List<AM_BasicInfoModel> allEmpModel = new List<AM_BasicInfoModel>();
        List<string> ApproverNames = new List<string>();

        // GET: AssetDashboard
        public ActionResult Index()
        {
            // get current use login id

            string UserId = Session["UserID"].ToString();

            // declare object to get current login user data
            List<AM_BasicInfoModel> EmpModel = new List<AM_BasicInfoModel>();

            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {
                AM_BasicInfoBal basicInfoBal = new AM_BasicInfoBal();
                EmpModel = basicInfoBal.GetCurrentLoginUser(clientContext, UserId);

                // get pending request data
                PendingReqModels = PendingReqBals.GetDataByEmpcode(clientContext,EmpModel[0].EmpCode);

                // get my request data
                MyRequestModels = MyRequestBal.GetMyRequest(clientContext, EmpModel[0].EmpCode);
            }

            // set current user empcode
            Session["CurUserEmpCode"] = EmpModel[0].EmpCode;

            /* add data to the model */
                // add pending request data
                assetMainModel.PendingRequest = PendingReqModels.OrderByDescending(i => i.ID);

                // add my request data
                assetMainModel.MyRequest = MyRequestModels.OrderByDescending(i => i.ID);

                // assign employee data get as per manager
                assetMainModel.BasicInfoModels = GetEmpInfo();

                // assign asset data
                assetMainModel.assetsModels = GetAssetsModels();

            return View(assetMainModel);
        }

        // call employee data as per manager
        [SharePointContextFilter]
        [ActionName("GetEmpInfo")]
        private List<AM_BasicInfoModel> GetEmpInfo()
        {
            string UserId = Session["UserID"].ToString();

            List<AM_BasicInfoModel> EmpModel = new List<AM_BasicInfoModel>();
            List<AM_BasicInfoModel> EmpByManager = new List<AM_BasicInfoModel>();

            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {
                AM_BasicInfoBal basicInfoBal = new AM_BasicInfoBal();
                AM_BasicInfoBal EmpDetails = new AM_BasicInfoBal();
                EmpModel = basicInfoBal.GetCurrentLoginUser(clientContext, UserId);
                EmpByManager = EmpDetails.GetEmpByManager(clientContext, (EmpModel[0].ID).ToString());
            }
            return EmpByManager;
        }

        // call assets data
        [SharePointContextFilter]
        [ActionName("GetAssetsModels")]
        private List<AM_AssetsModel> GetAssetsModels()
        {
            List<AM_AssetsModel> AssetModel = new List<AM_AssetsModel>();

            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {
                AM_AssetsBal assetsBal = new AM_AssetsBal();
                AssetModel = assetsBal.GetAssets(clientContext);
            }
            return AssetModel;
        }

        // call all employee data
        [SharePointContextFilter]
        [ActionName("GetAllEmpInfo")]
        private List<AM_BasicInfoModel> GetAllEmpInfo()
        {
            List<AM_BasicInfoModel> allEmpDataModel = new List<AM_BasicInfoModel>();
            AM_BasicInfoBal allEmpDataBal = new AM_BasicInfoBal();

            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {
                allEmpDataModel = allEmpDataBal.GetEmpData(clientContext);
            }
            return allEmpDataModel;
        }

        // call approver data
        public ActionResult GetApproveInfo(string EmpId)
        {
            string ecode = null;

            // get all employee information stored in session
            List<AM_BasicInfoModel> EmployeeArr = GetAllEmpInfo();

            for (int i = 0; i < EmployeeArr.Count; i++)
            {
                if (EmployeeArr[i].ID.ToString() == EmpId)
                {
                    ecode = EmployeeArr[i].EmpCode;
                }
            }


            // get approver data start

            // declare ApproverRoleName list object to get approvers data
            List<GEN_ApproverRoleNameModel> masterModel = new List<GEN_ApproverRoleNameModel>();

            // declare object to call approvers bal class
            GEN_ApproverMasterBal approverMasterBal = new GEN_ApproverMasterBal();

            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {

                string modulename = "Asset Management";
                string approvertype = "Main";

                masterModel = approverMasterBal.getApproverData(clientContext, ecode, modulename, approvertype);

                for (var i = 0; i < masterModel.Count; i++)
                {
                    for (int j = 0; j < EmployeeArr.Count; j++)
                    {
                        if (masterModel[i].Empcode == EmployeeArr[j].EmpCode)
                        {
                            masterModel[i].Title = EmployeeArr[j].FirstName + " " + EmployeeArr[j].LastName;
                        }
                    }
                }
            }

            // get approver data end

            // set session for approver data
            Session["masterModel"] = masterModel;

            return Json(masterModel, JsonRequestBehavior.AllowGet);
        }

        // call asset type data
        public ActionResult GetAssetType(AM_AssetsTypeModel assetTypeObj)
        {
            string assetTypeId = assetTypeObj.AssetType;

            List<AM_AssetsTypeModel> AssetModelType = new List<AM_AssetsTypeModel>();

            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {
                AM_AssetsTypeBal assetsBal = new AM_AssetsTypeBal();
                AssetModelType = assetsBal.GetAssetsType(clientContext, assetTypeId);
            }

            return Json(AssetModelType, JsonRequestBehavior.AllowGet);
        }

        // save asset data
        [HttpPost]
        public ActionResult SaveAssetData(AM_AssetsApplyModel assetsApplyModel)
        {
            string returnID = "0";

            // get all employee information stored in session
            List<AM_BasicInfoModel> EmployeeArr = GetAllEmpInfo();

            // get created name and created code
            string UserId = Session["UserID"].ToString();

            // get current user emp code
            string CurUserEmpCode = Session["CurUserEmpCode"].ToString();

            // declare ApproverRoleName list object to get approvers data
            List<GEN_ApproverRoleNameModel> masterModel = new List<GEN_ApproverRoleNameModel>();

            // get session of approver data
            masterModel = (List<GEN_ApproverRoleNameModel>)Session["masterModel"];

            // declare workflow list object to get workflow data
            List<AM_WorkFlowModel> workFlowModels = new List<AM_WorkFlowModel>();

            // store data in the applydetails array
            List<AM_AssetsApplyDetailsModel> assetsApplyDetailsModels = assetsApplyModel.applyDetailsModel;

            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPHost())
            {

                for (var i = 0; i < masterModel.Count; i++)
                {

AssetslnWeb/Views/AssetDashboard/AM_ApplyAssetView.cshtml
@model AssetslnWeb.Models.AssetManagement.AM_AssetMainModel

<form role="form" id="ApplyAssetForm">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title w-100" id="myModalLabel">Apply For Asset</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="row row-sm mg-b-30" id="showApprover">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <h5 class="card-title mb-3">Approver</h5>
                            <div class="row-fluid" id="approval-diagram" style="margin-bottom: 20px">
                                <ul class="breadcrumb" id="approverData">
                                    <li><a href="#">You</a></li>
                                </ul>
                                <!--<li><a href="#"><i class="fa fa-check"></i> Completed</a></li>-->
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row row-sm">
                    <div class="col-lg-12"><h5 class="card-title mb-3">Create a new request for Asset</h5></div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="First_Name">Employee Name</label>
                            <div id="slWrapper" class="parsley-select">
                                <select required="" class="form-control" name="EmployeeName" ng-model="ngddlAllUser" id="EmpSelect" onchange="getApproverInfo()" data-parsley-class-handler="#slWrapper" data-parsley-errors-container="#slErrorContainer">
                                    <option value=""> </option>
                                    @if (Model.BasicInfoModels.Count() > 0)
                                    {
                                        foreach (var obj in Model.BasicInfoModels)
                                        {
                                            <option value="@obj.ID">
                                                @obj.FirstName @obj.LastName
                                            </option>
                                        }
                                    }
                                </select>
                            </div>
                            <div id="slErrorContainer"></div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="exampleInputPassword1">Request Date</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <i class="typcn typcn-calendar-outline tx-24 lh--9 op-6"></i>
                                    </div>
                                </div><input class="form-control" ng-model="ngtxtRequestDate" id="requestdate" type="text" disabled>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="form-group">
                            <label for="exampleInputPassword1">Return Date</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <script src="~/assets/js/form-elements.js"></script>
                                        <i class="typcn typcn-calendar-outline tx-24 lh--9 op-6"></i>
                                    </div>
                                </div><input required="" class="form-control" ng-model="ngtxtReturnDate" id="returndate" autocomplete="off" type="text" data-parsley-class-handler="#slReturnDate" data-parsley-errors-container="#slReturnDateError">
                            </div>
                            <div id="slReturnDateError"></div>
                        </div>
                    </div>
                </div>

                <div></div>
                <div class="row row-sm">
                    <div class="col-lg-6"><h5 class="card-title mb-3">Add Assets</h5></div><div class="col-lg-6"></div>

                    <div class="table-responsive mg-b-30 text-center">
                        <table class="table table-bordered mg-b-0 text-md-nowrap bordertable">
                            <thead>
                                <tr>
                                    <th scope="col">Asset</th>
                                    <th scope="col">Asset Type</th>
                                    <th scope="col">Req Qty</th>
                                    <th scope="col">Reason To Apply</th>
                                    <th scope="col">Asset Details</th>
                                    <th scope="col">Replacement</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <select class="form-control validate" ng-model="ngddlAsset" id="ddlAsset" onchange="getAsset()">
                                            <option value=""></option>
                                            @if (Model.assetsModels.Count() > 0)
                                            {
                                                foreach (var j in Model.assetsModels)
                                                {
                                                    <option value="@j.ID">
                                                        @j.Assets
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </td>
                                    <td>
                                        <select class="form-control validate" ng-model="ngddlAssetType" id="ddlAssetType" ng-options="a.ID as a.AssetType for a in AssetType track by a.ID">
                                            <option value=""> </option>
                                        </select>
                                    </td>
                                    <td class="wd-10p"><input type="text" class="form-control validate" ng-model="ngtxtQty" id="txtQty" autocomplete="off" placeholder="Enter Req Qty"></td>
                                    <td><textarea class="form-control validate" ng-model="ngtxtReason" id="txtReason" placeholder="Enter Reason To Apply" rows="3"></textarea></td>
                                    <td><textarea class="form-control validate" ng-model="ngtxtDesc" id="txtDesc" placeholder="Enter Asset Details" rows="3"></textarea></td>
                                    <td>
                                        <select class="form-control validate" ng-model="ngddlReplacement" id="ddlReplacement">
                                            <option value=""> </option>
                                            <option value="Yes">Yes</option>
                                            <option value="No">No</option>
                                        </select>
                                    </td>
                                    <th scope="col">
                                        <button class="btn btn-info btn-block" type="button" ng-click="AddAssets()">Add</button>
                                    </th>
                                </tr>
                                <tr ng-repeat="i in AssetsArr track by $index">
                                    <td scope="row" data-label="Asset">{{i.Asset}}</td>
                                    <td data-label="AssetType">{{i.AssetType}}</td>
                                    <td data-label="Qty">{{i.UserApplyQuantity}}</td>
                                    <td data-label="Reason">{{i.ReasonToApply}}</td>
                                    <td data-label="Details">{{i.AssetDetails}}</td>
                                    <td data-label="Replacement">{{i.Replacement}}</td>
                                    <td scope="col"><button class="btn btn-info btn-block" type="button" ng-click="RemoveAssets($index)">Delete</button></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>


                <div class="row row-sm mg-b-20">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="First_Name">Comments</label>
                            <textarea required="" class="form-control" ng-model="ngtxtComment" id="txtComment" placeholder="Enter Comment" rows="3"></textarea>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>

AssetslnWeb/Views/AssetDashboard/AM_DashboardView.cshtml
@model AssetslnWeb.Models.AssetManagement.AM_AssetMainModel


<!-- Pending Dashboard Code start-->
    <div>
        <div class="card mg-b-20">
            <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title mg-b-0">My Pending Request</h4>
                </div>
            </div>

            <div class="card-body">

                <div class="row-sm text-center">
                    <div class="col-sm-6 col-md-2 mg-b-20 float-right">
                        <button type="button" class="btn btn-primary addbtn1 float-right" onclick="ApplyAsset()"><i class="fa fa-plus AddPlus"></i> Apply For Asset</button>
                        @*@Ajax.ActionLink("Apply For Asset", "ApplyAssetView", "AssetDashboard", new AjaxOptions { UpdateTargetId = "ApplyAssetData" }, new { @class = "btn btn-primary addbtn1 float-right" })*@
                    </div>
                </div>


                <div class="table-responsive">
                    <table id="pendingrequest" class="table key-buttons text-md-nowrap">
                        <thead>
                            <tr>
                                <th class="wd-10p border-bottom-0">Sr. No.</th>
                                <th class="wd-20p border-bottom-0">Request No</th>
                                <th class="wd-20p border-bottom-0">Employee Name</th>
                                <th class="wd-15p border-bottom-0">Status</th>
                                <th class="wd-15p border-bottom-0">Request Date</th>
                                <th class="wd-15p bottom-0">Return Date</th>
                                <th class="wd-15p border-bottom-0">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int index = 1;}
                            @foreach (var j in Model.PendingRequest)
                            {
                                <tr>
                                    <td>@index</td>
                                    <td>@j.RequestNo</td>
                                    <td>@j.fname @j.lname</td>
                                    <td><span class="badge badge-dark">@j.Status</span></td>
                                    <td>@(j.RequestDate.ToString("dd/MM/yyyy"))</td>
                                    <td>@(j.ReturnDate.ToString("dd/MM/yyyy"))</td>
                                    <td>
                                        <button class="btn btn-icon-list" onclick="getViewData(@j.ID)" style="padding:0px;">
                                            <i class="si si-pencil text-primary mr-2" data-toggle="tooltip" title="" data-placement="top" data-original-title="Edit"></i>
                                        </button>
                                    </td>
                                </tr>
                                index++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Pending Dashboard Code End-->
        <!-- My Request Dashboard Code start-->
        <div class="card mg-b-20">
            <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title mg-b-0">My Request</h4>
                </div>
            </div>

            <div class="card-body">


                <div class="table-responsive">
                    <table id="myrequest" class="table key-buttons text-md-nowrap">
                        <thead>
                            <tr>
                                <th class="wd-10p border-bottom-0">Sr. No.</th>
                                <th class="wd-20p border-bottom-0">Request No</th>
                                <th class="wd-20p border-bottom-0">Employee Name</th>
                                <th class="wd-15p border-bottom-0">Status</th>
                                <th class="wd-15p border-bottom-0">Request Date</th>
                                <th class="wd-15p border-bottom-0">Return Date</th>
                                <th class="wd-15p border-bottom-0">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int indexview = 1;}
                            @foreach (var j in Model.MyRequest)
                            {
                                <tr>
                                    <td>@indexview</td>
                                    <td>@j.RequestNo</td>
                                    <td>@j.fname @j.lname</td>
                                    <td><span class="badge badge-dark">@j.Status</span></td>
                                    <td>@(j.RequestDate.ToString("dd/MM/yyyy"))</td>
                                    <td>@(j.ReturnDate.ToString("dd/MM/yyyy"))</td>
                                    <td>
                                        <button class="btn btn-icon-list" onclick="getViewData(@j.ID,'view')" style="padding:0px;">
                                            <i class="si si-eye text-success mr-2" data-toggle="tooltip" title="" data-placement="top" data-original-title="View"></i>
                                        </button>
                                    </td>
                                </tr>
                                indexview++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- My Request Dashboard Code End-->



        <script>
            $('#pendingrequest').DataTable({
                responsive: true,
                language: {
                    searchPlaceholder: 'Search...',
                    sSearch: '',
                    lengthMenu: '_MENU_',
                }
            });

            $('#myrequest').DataTable({
                responsive: true,
                language: {
                    searchPlaceholder: 'Search...',
                    sSearch: '',
                    lengthMenu: '_MENU_',
                }
            });
        </script>
    </div>

AssetslnWeb/Views/AssetDashboard/Index.cshtml
@model AssetslnWeb.Models.AssetManagement.AM_AssetMainModel

@section style{

    <!--Internal  Datetimepicker-slider css -->
    <link href="~/assets/plugins/amazeui-datetimepicker/css/amazeui.datetimepicker.css" rel="stylesheet" />

    <!-- Internal Select2 css -->
    <link href="~/assets/plugins/select2/css/select2.min.css" rel="stylesheet">

    <!-- Internal Data table css -->
    <link href="../assets/plugins/datatable/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="../assets/plugins/datatable/css/buttons.bootstrap4.min.css" rel="stylesheet">
    <link href="../assets/plugins/datatable/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    <link href="../assets/plugins/datatable/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="../assets/plugins/datatable/css/responsive.dataTables.min.css" rel="stylesheet">

    <!--Internal   Notify -->
    <link href="../assets/plugins/notify/css/notifIt.css" rel="stylesheet" />

}

<!-- container opened -->
<div class="container" ng-app="AssetDashboardapp" ng-controller="AssetDashboardController">
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">Asset Management</h4><span class="text-muted mt-1 tx-13 ml-2 mb-0">/ Dashboard</span>
            </div>
        </div>
    </div>
    <!-- breadcrumb -->
    <!-- row -->
    <div class="row">
        <div class="col-xl-12 col-lg-12" id="AssetDashboardModel">
            @Html.Partial("AM_DashboardView", Model)
        </div>
    </div>
    <!-- row closed -->
    <!-- apply asset modal pop up -->
    <!-- Full Height Modal Right -->
    <div class="modal left fade" id="ModalPopUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-keyboard="false" data-backdrop="static"
         aria-hidden="true">
        @Html.Partial("AM_ApplyAssetView", Model)
    </div>
    <!-- Full Height Modal Right -->
    <!-- end apply asset modal pop up -->


    <!-- asset view modal pop up -->
    <!-- Full Height Modal Right -->
    <div class="modal left fade" id="ModalViewPopUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-keyboard="false" data-backdrop="static"
         aria-hidden="true">
        @Html.Partial("AM_AssetView", Model)
    </div>
    <!-- Full Height Modal Right -->
    <!-- end apply view modal pop up -->


</div>
<!-- Container closed -->


@section scripts{

    <!-- Internal Select2.min js -->
    <script src="~/assets/plugins/select2/js/select2.min.js"></script>
    <script src="~/assets/js/select2.js"></script>

    <!--Internal  Parsley.min js -->
    <script src="../assets/plugins/parsleyjs/parsley.min.js"></script>

    <!--Internal  jquery-simple-datetimepicker js -->
    <script src="~/assets/plugins/amazeui-datetimepicker/js/amazeui.datetimepicker.min.js"></script>
    <script src="~/assets/js/datePicker.js"></script>

    <!--Internal  Notify js -->
    <script src="../assets/plugins/notify/js/notifIt.js"></script>

    <!-- Internal Data tables -->
    <script src="../assets/plugins/datatable/js/jquery.dataTables.min.js"></script>
    <script src="../assets/plugins/datatable/js/dataTables.dataTables.min.js"></script>
    <script src="../assets/plugins/datatable/js/dataTables.responsive.min.js"></script>
    <script src="../assets/plugins/datatable/js/responsive.dataTables.min.js"></script>
    <script src="../assets/plugins/datatable/js/jquery.dataTables.js"></script>
    <script src="../assets/plugins/datatable/js/dataTables.bootstrap4.js"></script>
    <script src="../assets/plugins/datatable/js/dataTables.buttons.min.js"></script>
    <script src="../assets/plugins/datatable/js/buttons.bootstrap4.min.js"></script>
    <script src="../assets/plugins/datatable/js/jszip.min.js"></script>
    <script src="../assets/plugins/datatable/js/pdfmake.min.js"></script>
    <script src="../assets/plugins/datatable/js/vfs_fonts.js"></script>
    <script src="../assets/plugins/datatable/js/buttons.html5.min.js"></script>
    <script src="../assets/plugins/datatable/js/buttons.print.min.js"></script>
    <script src="../assets/plugins/datatable/js/buttons.colVis.min.js"></script>
    <script src="../assets/plugins/datatable/js/dataTables.responsive.min.js"></script>
    <script src="../assets/plugins/datatable/js/responsive.bootstrap4.min.js"></script>

    <!--Internal  Datatable js -->
    <script src="../assets/js/table-data.js"></script>

    <script src="~/Scripts/Angular/AssetManagement/JS/AssetDashboard.js"></script>

    <script>
        $('#pendingrequest').DataTable({
            responsive: true,
            language: {
                searchPlaceholder: 'Search...',
                sSearch: '',
                lengthMenu: '_MENU_',
            }
        });

        $('#myrequest').DataTable({
            responsive: true,
            language: {
                searchPlaceholder: 'Search...',
                sSearch: '',
                lengthMenu: '_MENU_',
            }
        });
    </script>
}